### ISSUE TITLE
El botón no funciona

### ISSUE THREAD

**Issue by pepas24** [proyectosebastianandres/practica-git#10]
En la consola del navegador aparece este error
`TypeError: document.getElementById(...) is null`

**Comment by andres0107** [comment]
Ya quedó solucionado, el commit de referencia al cambio es 3b7e9dd8a7687236ca13ce511af26b79ae9fd93c

**Comment by andres0107** [comment]
Ya quedó solucionado, el commit de referencia al cambio es 3b7e9dd
